### ISSUE TITLE
Unable to cast object of type 'MySql.Data.MySqlClient.MySqlConnection' to type 'System.Data.SqlClient.SqlConnection'.'

### ISSUE THREAD

**Issue by aydoo** [tiagoln/BulkExtensions#11]
Hello, first of all thanks for this tool, it's exactly what I need. :)

Unfortunately, when I try to use ccontext.BulkInsert(...) I keep getting "Unable to cast object of type 'MySql.Data.MySqlClient.MySqlConnection' to type 'System.Data.SqlClient.SqlConnection'.'" If I use the regular way with context.SaveChanges, it works fine.

I use VS17 with ASP.Net Core and EF Core.

**Comment by tiagoln** [comment]
I noticed this 'MySql.Data.MySqlClient.MySqlConnection'. Sadly MySql is not supported, this library relies purely on the SqlBulkCopy API witch only supports SqlServer. I currently have no plans to support other database for now, but I'll look in to it. Thanks for the interest.

**Comment by aydoo** [comment]
Ah alright that makes sense. Do you happen to know an alternative that does offer the same functionality for MySQL?

**Comment by tiagoln** [comment]
I don't know, sorry. But I was looking for how to implement support for MySQL and it seems doable, but differently from SqlBulkCopy, which inserts a DataTable object(or IDataReader) directly to the database, the MySqlBulkLoader class needs to read the data from a CVS file, so the data has to be written on a CVS file before.
This is the first step, as the SQL code is also different for MySQL, it needs to be re-written as it do not have the 'MERGE' command used to perform the bulk operations. I'll see if I can do a MySQL version of the library in the future.
You can take a look at this article to have an idea [MySqlBulkLoader example](https://dev.mysql.com/doc/connector-net/en/connector-net-programming-bulk-loader.html)

**Comment by gtaylor44** [comment]
Entity Framework Extensions has support for MySQL... http://entityframework-extensions.net/
