### ISSUE TITLE
Computed properties support

### ISSUE THREAD

**Issue by 4nonym0us** [tiagoln/BulkExtensions#12]
Mapping computed properties isn't supported.

Sample computed property:
```csharp

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public double SampleProperty
        {
            get { return 0/*insert any calculation here*/; }
            private set
            {
                //Just need this here to trick EF
            }
        }
```
ORM: EF6

Executing any bulk operation on such an entity will cause SqlException, which says that it's impossible to insert NULL value of property `SampleProperty` into table.

**Comment by tiagoln** [comment]
Thanks for reporting, I'll fix that. Computed properties shouldn't be inserted, that's a bug. But do you think it would be interesting that they could be populated, as the generated ids are with the 'InsertOptions.OutputIdentity', with a new 'InsertOptions.OutputComputed' flag?

**Comment by 4nonym0us** [comment]
I think that property population should should be made by default because It's expected behavior. Otherwise, having a 'InsertOptions.OutputComputed' flag would be great.

**Comment by tiagoln** [comment]
I though of putting as optional cause it has less performance than plain insert, as it adds an overhead to output the values, just like generated Id population, this way the user has more flexibility as he can choose.

**Comment by 4nonym0us** [comment]
From this point of view, I must admit that you are absolutely right. It looks like having an additional flag should be better solution because of the same reason. Having different flags for Identity and Computed column would provide more control over the bulk operation.

**Comment by sadande** [comment]
I have complex relational DB design (Parent- Sub child's - child) one to many with primary key and foreign key relations on each. When I execute the context.BulkInsert(entityList); it only inserts data in first parent table and nothing to its sub related tables.

Can you please let me know whether BulkExtensions supports one to many relations design??

I have approx 30K records which i need to save it to DB and i am looking for a faster process to save the changes via EF6

Your response will be greatly appreciated, Thanks in advance!!

-Sachin

**Comment by tiagoln** [comment]
I have implemented proper computed columns support on the new version, check it out.
