### ISSUE TITLE
SQL Server 2005 currently not supported

### ISSUE THREAD

**Issue by egleiser** [tiagoln/BulkExtensions#13]
I receive the following error when attempting to use context.BulkInsertOrUpdate() with EF6.
Is this possibly because of SQL Server 2005?

Looking at the code it likely because it uses MERGE which is not supported in SQL Server 2005.
Maybe these articles can be of help to provide legacy support.
(http://sqlserver-tips.blogspot.com/2006/09/mimicking-merge-statement-in-sql.html)
(http://programmersedge.azurewebsites.net/?p=821)
(https://dba.stackexchange.com/questions/118455/merge-command-in-sql-server-2005)

Using the standard (and slow) context.foos.AddOrUpdate(foo);
Works fine.

There is also a chance in my code that BulkInsertOrUpdate can be called by another thread at the same time.

`System.Data.SqlClient.SqlException occurred
  HResult=0x80131904
  Message=Incorrect syntax near the keyword 'INTO'.
Incorrect syntax near the keyword 'with'. If this statement is a common table expression or an xmlnamespaces clause, the previous statement must be terminated with a semicolon.
  Source=.Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
`

Let me know what you think!
Thanks!

**Comment by tiagoln** [comment]
> Looking at the code it likely because it uses MERGE which is not supported in SQL Server 2005.
Maybe these articles can be of help to provide legacy support.

Yes, that's right, SQL Server 2005 is not supported because of that. I'll take a look at those articles but I'll make no promises, currently I'm implementing other features.
