### ISSUE TITLE
Bulkinsert for one to many DB relationships

### ISSUE THREAD

**Issue by sadande** [tiagoln/BulkExtensions#14]
I have complex relational DB design (Parent- Sub child's - child) one to many with primary key and foreign key relations on each. When I execute the context.BulkInsert(entityList); it only inserts data in first parent table and nothing to its sub related tables.

Can you please let me know whether BulkExtensions supports one to many relational design??

I have approx 30K records which i need to save it to DB and i am looking for a faster process to save the changes via EF6

Your response will be greatly appreciated, Thanks in advance!!

-Sachin

**Comment by tiagoln** [comment]
The library do not support navigation properties(used to map relationships), it cannot handle more than one table at a single trip, as I mentioned on the project's main page. But there's a workaround, mentioned on the main page as well. 

I have a scenario on a project at work with the same relational structure as yours (Parent- Sub child's - child), In fact, I began this library project to solve this very issue. 

To solve it using the BulkExtensions library you'll have to make one BulkInsert call for each class, in this case there will be 3 calls, starting from the higher in the hierarchy all the way to the bottom. You need to BulkInsert the Parent outputting the generated Id, then set the Id on the foreign key of the SubChild and BulkInsert them also outputting the Id, set it on the foreign key of the Child and BulkInsert them. Look at this example.

```c#
public void SaveMyComplexScenario(IEnumerable<Parent> parentList) {
     //BulkInsert the Parent list outputting the generated Ids
     context.BulkInsert(parentList, InsertOptions.OutputIdentity);
     
     //Set the Ids of the Parents on the SubChilds foreign key
     parentList.ToList().ForEach(parent => {
          parent.SubChildList.ToList().ForEach(subChild => {
               subChild.ParentId = parent.Id;
          })
     });

     //BulkInsert the SubChilds outputting the generated Ids 
     var allSubChildList = parentList.SelectMany(parent => parent.SubChildList);
     context.BulkInsert(allSubChildList, InsertOptions.OutputIdentity);

     //Set the Ids of the SubChilds on the Childs foreign key
     allSubChildList.ToList().ForEach(subChild => {
          subChild.ChildList.ToList().ForEach(child => {
               child.SubChildId = subChild.Id;
          })
     });

     //BulkInsert the Childs 
     var allChildList = allSubChilds.SelectMany(subChild => subChild.ChildList);
     context.BulkInsert(allChildList);
}

```
Regarding performance I had no issues in my project using this approach. But if you want to speed up the process of setting the Ids on the foreign keys you can switch the ForEach by a Parallel.Foreach.

**Comment by sadande** [comment]
Thanks for your quick response and suggestion, I do understand the approach you have suggested but i don't think for me inserting each table will work out due to my complex DB design. 

-Sachin

**Comment by tiagoln** [comment]
I see. As I mentioned, the solution I proposed works well for a straight forward Parent -> SubChild -> Child scenario at my work, but if there are other relationships involved you'll need another approach. I hope you can find a solution. In any case, I'll be glad to help with any further questions. =)
