### ISSUE TITLE
BulkUpdate and snapshot isolation level

### ISSUE THREAD

**Issue by GLeBaTi** [tiagoln/BulkExtensions#17]
Hi.
I have this situation:
```
context = new IUMobileDbContext();
transaction = context.Database.BeginTransaction(IsolationLevel.Snapshot);

{{ MY CODE HERE }}

context.SaveChanges();
try
{
   transaction.Commit();
}
catch
{
   transaction.Rollback();
   throw;
}
finally
{
   transaction.Dispose();
}
```

If i have this code in different transaction (in one time), i will catch DbUpdateConcurrencyException. (This is normal. I want this):
```
transaction1: {{ john.Money = 20; context.Set<User>().AddOrUpdate(john); }}
transaction2: {{ john.Money = 10; context.Set<User>().AddOrUpdate(john); }}
```

But. If i do this by BulkUpdate, i have no exceptions, and in result john = 10; (I want exception):
```
transaction1: 
{{ 
john.Money = 20; 
context.Set<User>().AddOrUpdate(john); 
}}
transaction2: 
{{ 
john.Money = 10;
EntityFramework.BulkExtensions.Operations.BulkExtensions.BulkUpdate(context, List<User>(){john});
}}
```

How can i prevent overwrites and throw exeption on collisions?

**Comment by tiagoln** [comment]
Hi, I'm a little overwhelmed with stuff to do today, but as soon as I can I'll try to reproduce this concurrency scenario and see what I can do.

**Comment by tiagoln** [comment]
I didn't understand this part:
```
transaction2: 
{{ 
john.Money = 10; context.Set<User>().AddOrUpdate(john);
EntityFramework.BulkExtensions.Operations.BulkExtensions.BulkUpdate(context, List<User>(){john});
}}
```
If you are going to update 'john' using the BulkUpdate command you don't need to call `context.Set<User>().AddOrUpdate(john);`  beforehand, just call the BulkUpdate directly.

Another question on the same transaction2 situation, somewhere before calling this line:
>EntityFramework.BulkExtensions.Operations.BulkExtensions.BulkUpdate(context, List<User>(){john}); 

are you calling `context.Database.BeginTransaction(IsolationLevel.Snapshot);`?

**Comment by GLeBaTi** [comment]
1) sorry, i forgot remove this line (edited)
2) yes, beginTransaction in beginning (see first code sample)

**Comment by GLeBaTi** [comment]
https://pastebin.com/fZKVjA7J

**Comment by tiagoln** [comment]
OK, I'll try to reproduce this scenario to see what happens. 

Just for reference, as the library is implemented as extension methods of the DbContext class you don't need to call it like this:
>EntityFramework.BulkExtensions.BulkExtensions.BulkUpdate(context, List<User>(){john});

You can call it like this:
>context.BulkUpdate(List<User>(){john});

Also, you should not call the `context.SaveChanges();` method after the BulkUpdate, it will trigger the update through normal Entity Framework behavior, because of the change tracker, it can cause undesired effects, so you should not use it after the BulkUpdate call, you can safely remove it.

**Comment by tiagoln** [comment]
I've done some testings and reached some conclusions.

- [DbUpdateConcurrencyException ](https://msdn.microsoft.com/en-us/library/system.data.entity.infrastructure.dbupdateconcurrencyexception(v=vs.113).aspx)is not related to the isolation level of the transaction, it is an exception thrown by EF when you try to update an entity that has been updated elsewhere after you read it's value, when you call SaveChanges(). This is what the documentation says about the inner workings:
>Exception thrown by DbContext when it was expected that SaveChanges for an entity would result in a database update but in fact no rows in the database were affected. This usually indicates that the database has been concurrently updated such that a concurrency token that was expected to match did not actually match. Note that state entries referenced by this exception are not serialized due to security and accesses to the state entries after serialization will return null.

- The isolation level deals only with data reads and for this purpose it works as intended with the example you gave;
- The library's bulk operations do not interact with SaveChanges() or the EF change tracking, it only access mapping metadata of the entities stored on EF, so it will not raise any DbUpdateConcurrencyException;

So, unfortunately, if you are using any bulk operation the concurrency write will be 'client wins'.

**Comment by GLeBaTi** [comment]
Sorry, i mixed up.
Not DbUpdateConcurrencyException. 
SQLException must be. :

> Snapshot isolation transaction aborted due to update conflict. You cannot use snapshot isolation to access table 'dbo.Users' directly or indirectly in database 'myDatabase' to update, delete, or insert the row that has been modified or deleted by another transaction. Retry the transaction or change the isolation level for the update/delete statement.

**Comment by GLeBaTi** [comment]
But not. 
The problem is urgent at the moment.
