### ISSUE TITLE
Incompatible with .Net Core 1.0

### ISSUE THREAD

**Issue by afshany** [tiagoln/BulkExtensions#18]
Hi,

I just trying to download the package in a net core 1.0 project and got this error:
..Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.0.

does it support net core? I've read it here :https://tiagoln.github.io/BulkExtensions/  that it does.

**Comment by tiagoln** [comment]
Did you tried this package [https://www.nuget.org/packages/EntityFramework.BulkExtensions.EFCore](https://www.nuget.org/packages/EntityFramework.BulkExtensions.EFCore)? It's compiled as a .Net Standard 1.3 library, I have it installed on a .NetCoreApp 1.0 app without any issues.

**Comment by afshany** [comment]
Yes. that's the one I tried. anyone else has the same issue? This is the error message detail:

Install-Package : Package EntityFramework 6.1.3 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package EntityFramework 6.1.3 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package EntityFramework.BulkExtensions -Version 1.3.5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with .NETStandard,Version=v1.6.

**Comment by tiagoln** [comment]
Actually, you are installing the wrong package and not the link I posted before, that one is for the correct version, try that one. 

This library has 2 distinct packages, one for Entity Framework 6(which works only on .Net Framework), and one for Entity Framework Core(which works on .Net Framework AND .NetCore).

Take a look at this passage of your log, you are trying to install the EF6 one, it is not for .NetCore, EF6 only works on .Net Framework:
>Install-Package EntityFramework.BulkExtensions -Version 1.3.5

The two packages are:
- [EntityFramework.BulkExtensions](https://www.nuget.org/packages/EntityFramework.BulkExtensions) for EF6;

- [EntityFramework.BulkExtensions.EFCore](https://www.nuget.org/packages/EntityFramework.BulkExtensions.EFCore) for EFCore;

The two packed are documented here [https://tiagoln.github.io/BulkExtensions/](https://tiagoln.github.io/BulkExtensions/)

**Comment by afshany** [comment]
Thanks!!

**Comment by tiagoln** [comment]
You're welcome. =)
