### ISSUE TITLE
TPH

### ISSUE THREAD

**Issue by Shino67** [tiagoln/BulkExtensions#23]
In case of TPH, every Bulk operation fail because the following code (from mappingExtension when getting associated mapping):

            var entitySet = metadata
                .GetItems<EntityContainer>(DataSpace.CSpace)
                .Single()
                .EntitySets
                .Single(s => s.ElementType.Name == entityType.Name);

throw an exception.. (in fact, in TPH case, the entity name does not exists in entitySet, only the parent class is available).
How to handle this case?
I Have the following structure:
class A{}
class B : A {}
class C: B {}.
I would like to BulkInsert many objects of type C.

Thank you for your help :) Good Afternoon.

Alex

**Comment by tiagoln** [comment]
Hi @Shino67, I'll reproduce this scenario here to see what's happening.

**Comment by Shino67** [comment]
Thank you very much for your reactivity and your workaround! :)
Looking for the next release ^^.

Have a good day

**Comment by tiagoln** [comment]
There's a new version that should fix this, check it out.
