### ISSUE TITLE
BulkInsertOrUpdate fails when entity only has ID property

### ISSUE THREAD

**Issue by JamesLowes** [tiagoln/BulkExtensions#24]
I have an entity like:

```
public long Id { get; set; }
public virtual ICollection<OtherThing> OtherThings { get; set; }
```
Basically its meant to represent a grouping of "OtherThing"s with an ID (I'm inserting the "'OtherThing"s separately with this ID of the group as foreign key).

However, I'm getting a syntax error when trying to use BulkInsertOrUpdate with these entities:
`System.Data.SqlClient.SqlException: 'Incorrect syntax near the keyword 'WHEN'.'`

After adding an extra property to the entity, (e.g.: `public string GroupName { get; set; }`) the entities are inserted correctly.

**Comment by tiagoln** [comment]
Thanks for reporting, I checked out and found the issue, fixed it. The fix will be included on the next version. =D

**Comment by JamesLowes** [comment]
Thanks! Impressed with your response!

**Comment by tiagoln** [comment]
I've released a new version that should fix this issue, check it out.
