### ISSUE TITLE
BulkUpdate error (1.4.0 Core version)

### ISSUE THREAD

**Issue by daveyjay** [tiagoln/BulkExtensions#26]
I am getting an error when trying to do a BulkUpdate.

I am getting this error message:
``System.Data.SqlClient.SqlException: 'Cannot update identity column 'Id'.'``

Here is my code:

`var idList = new List<int>(myListOfPersons.Select(p => p.EmployeeId));`
`var employees = context.Set<Employee>().Where(c => idList.Contains(c.Id)).ToList();`
`foreach (var employee in employees)`
`{`
 `   employee.LastReviewDate = DateTime.Now;`
` }`
` context.BulkUpdate(employees); // error updating trying to update Id property happens here`

I don't understand why the the update is including the Id property.

In my code the myListOfPersons is a base class and the Employee is a sub class.  Wondering if the reason it isn't working is because of TPH?

**Comment by daveyjay** [comment]
Forgot to mention:
I am on version 1.4.0 of EntityFramework.BulkExtensions.EFCore.

**Comment by tiagoln** [comment]
Is your Id database generated?

**Comment by daveyjay** [comment]
Yes, the Id column is marked as IDENTITY.

The EF migration when scripted looks like this: 

`CREATE TABLE [BaseClassEntity] (
        [Id] int NOT NULL IDENTITY,`

**Comment by tiagoln** [comment]
Hmm, I see, can you post your entity? I'll try to reproduce the bug tomorrow, but it is probably related to the bug I mentioned.

**Comment by daveyjay** [comment]
Here are the entities and relationships


`public class Person 
{`
     `    public int Id {get; set;}`
`  public string FirstName { get; set; } `
` public string LastName { get; set; }` 
` public Employee Employee { get; set; }`
` public int EmployeeId { get; set; } `

}`

`public class Employee`
`{`
`   public int Id { get; set; }`
`   public string EmployeeNumber { get; set; }`
`  public bool  IsPartTime  { get; set; }`
` public DateTime LastReviewDate { get; set; }`

`}`

**Comment by tiagoln** [comment]
Do you annotate the Ids or do you use fluent api?

**Comment by daveyjay** [comment]
For EF Core - we have not annotated the Id property - we are just using the field "Id" using that exact wording as convention and the code first migration generates Identity columns for us.

For other configurations, we are using Fluent API but we have not explicitly specified the key value.

**Comment by tiagoln** [comment]
Ok, thanks for the info, it'll help me reproduce the issue.

**Comment by tiagoln** [comment]
@daveyjay I have released a new version to fix this issue, it indeed was related to the issue I've mentioned before. Update and it should work fine. =D

**Comment by daveyjay** [comment]
Thank you - just did the update and everything working great! :-)

**Comment by tiagoln** [comment]
You're welcome, glad to hear everything is working! =D
