### ISSUE TITLE
BulkInsert fails with error cannot insert because column ID cannot accept null (Core version)

### ISSUE THREAD

**Issue by afshany** [tiagoln/BulkExtensions#27]
Hi,

I am getting the exception when using BulkInsert even thought all the fields have value. I just found that some people had the same issue before, have you made the fix for core version as well?

P.S: I have a primary key and two foreign keys both have value
Thanks

**Comment by tiagoln** [comment]
Hi there!
First I need some context, can you post your entity? Your Id is database generated?

**Comment by afshany** [comment]
Here is the entity:(Id is not generated by db, I pass it)   


 public class Design
    {
        [Key]
        [MaxLength(50)]
        public string design_id { get; set; }
        [MaxLength(40)]
        public string design_name { get; set; }
        public string description { get; set; }

        public int request_id { get; set; }
        [ForeignKey("request_id")]
        public virtual Request Request { get; set; }

        public string selected_solution_id { get; set; }
        [ForeignKey("selected_solution_id"),]
        public virtual Solution Solution { get; set; }

    }

**Comment by tiagoln** [comment]
It is a behavior of the EFCore mapping api, the api only holds information about the database that are provided by the user (the library uses mapping provided only by the EFCore mapping api), it do not have information that are defined only on the database side, so you'll have to add to the _design_id_  annotation the info that your Id is not generated by the database, this will provide the EFCore mapping api with the right configuration of your database.

To fix this behavior you have to annotate the _design_id_ property like this `[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]`.

In your entity it should look like this:
```c#
public class Design
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
    [MaxLength(50)]
    public string design_id { get; set; }
    
    [MaxLength(40)]
    public string design_name { get; set; }
    public string description { get; set; }

    public int request_id { get; set; }
    [ForeignKey("request_id")]
    public virtual Request Request { get; set; }

    public string selected_solution_id { get; set; }
    [ForeignKey("selected_solution_id"),]
    public virtual Solution Solution { get; set; }

}
```

**Comment by afshany** [comment]
you are absolutely right! great catch. thanks!

**Comment by tiagoln** [comment]
Glad I could help =D
