### ISSUE TITLE
Exception - Sequence contains no elements

### ISSUE THREAD

**Issue by rhgs** [tiagoln/BulkExtensions#30]
When IsHierarchyMapping==true but have no rows in  typeMapping.Fragments.First().Conditions .
Method: GetHierarchyMappings
Class: MappingExtension

**Comment by tiagoln** [comment]
Hi there,
I need morre information about your scenario to figure out what's happening? What are your entities? Are you using TPH, TPT or TPC?

**Comment by rhgs** [comment]
Hi!

I'm using EF6 and CodeFirst with migrations enable.

My model looks like:

```
namespace UnitTests.EF6.Model
{
    [Table("Person")]
    public class Person
    {
        [Key]
        public int Id { get; set; }

        [Column("Nome"), Required]
        public string Name { get; set; }

        public DateTime Birthday { get; set; }
    }

    [Table("Employee")]
    public class Employee : Person
    {
        public string JobTitle { get; set; }
    }
}
```

And the UnitTest is:

` public class EF6_TpcBulkInsert : IDisposable
    {
        private readonly TestDatabase _context;
        private readonly IList<Employee> _collection;

        public EF6_TpcBulkInsert()
        {
            _context = new TestDatabase();
            ClearTable();
            _collection = new List<Employee>();
            for (var i = 0; i < 10; i++)
            {
                _collection.Add(new Employee
                {
                    Name = Helper.RandomString(10),
                    Birthday = DateTime.Today,
                    JobTitle = Helper.RandomString(5)
                }); ;
            }
        }


        [Fact]
        public void TestAffectedRowsCount()
        {
            var rowsCount = _context.BulkInsert(_collection);
            Assert.Equal(rowsCount, _collection.Count);
        }

        public void Dispose()
        {
            ClearTable();
            _context.Dispose();
        }
        private void ClearTable()
        {
            _context.Employee.RemoveRange(_context.Employee.ToList());
            _context.SaveChanges();
        }
    }`

**Comment by tiagoln** [comment]
The problem is that you're using TPT(Table-per-Type) strategy, which is not currently supported. Unfortunately I have no road map for this feature as I am evaluating the issues of implementing this feature as I've mentioned [here](https://github.com/tiagoln/BulkExtensions/issues/29#issuecomment-313105344)

**Comment by rhgs** [comment]
Thanks @tiagoln !
