### ISSUE TITLE
SQL CE 4.0 is not supported?

### ISSUE THREAD

**Issue by bencevegert** [tiagoln/BulkExtensions#32]
Hy!
SQL CE 4.0 is not supported because of the SQLBulkCopy is not support CE databases?

We get this error:
SqlCeCommand.CommandTimeout does not support non-zero values

Thanks.

**Comment by ErikEJ** [comment]
@bencevegert Use my SqlCeBukCopy library for BULK INSERTS with SQL Server Compact: https://github.com/ErikEJ/SqlCeBulkCopy

**Comment by tiagoln** [comment]
@bencevegert  Hi there, besides the lack of SQLBulkCopy support, I believe SQL CE also do not support the "MERGE" statement, so, unfortunately, I have no current plans for implementing support for SQL CE in the near future, but I'll do some research to see if it is feasible for a later release, right now you could use the library provided by @ErikEJ.
