### ISSUE TITLE
Issue running when used with strong name assemblies

### ISSUE THREAD

**Issue by dberroa** [tiagoln/BulkExtensions#33]
We sign our dlls that we are trying to use BulkExtensions in. When running the project I get the error:

Message = "Could not load file or assembly 'EntityFramework.BulkExtensions, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)"

This can be fixed by signing the assembly with a strong name. Would it be possible for you to sign and give the dll a strong name and release a new version on nuget?

Once it has a strong name, the error will disappear for me.

**Comment by tiagoln** [comment]
Hi there, I'll take a look at it as soon as I can.

**Comment by dberroa** [comment]
Hey,

Do you have a time estimate when this might be looked into? I am unable to continue my project at the moment due to this.

**Comment by tiagoln** [comment]
Hey there, I'm a little overloaded with things at work this week, but I'll try do release a new version on nuget by Monday, maybe earlier.

**Comment by dberroa** [comment]
Is this updated in nuget? I don't see the update in the nuget package manager.

**Comment by tiagoln** [comment]
Hi there, I've just pushed new versions of the nuget packages, you can try now and see if it work as intended.

**Comment by dberroa** [comment]
I was able to load and use it. Thanks.

**Comment by tiagoln** [comment]
Nice! You're welcome.
