### ISSUE TITLE
Use actual temporary tables for the mirror tables

### ISSUE THREAD

**Issue by Arithmomaniac** [tiagoln/BulkExtensions#34]
Looking at [SqlHelper](https://github.com/tiagoln/BulkExtensions/blob/ab00c6d33d7651e6f57767a4992c8e58d885281c/BulkExtensions.Shared/Helpers/SqlHelper.cs#L27), the temporary table is not an actual temp table. Allowing to do so (even as an operation option) would avoid problems with users who do not have permission to create tables.

**Comment by tiagoln** [comment]
Hi there! 
Thanks for the tip, I think I'll make them Local temporary tables by default, that should be fine, don't you think?
