### ISSUE TITLE
Issue with performing two queries in a TransactionScope

### ISSUE THREAD

**Issue by dberroa** [tiagoln/BulkExtensions#36]
I am trying to insert a list and update a list of entities for Entity Framework 6. i wrap this in a using statement creating a TransactionScope variable.

When I test, I get no errors stating anything is wrong however whatever code runs second does not get run in the database. For example if I do bulkinsert followed by bulkupdate, bulkupdate doesn't do anything. If bulkinsert is second then it doesn't do anything.

I also noticed different behavior when I do a normal db.Add for a single item and then the bulkdelete after. When I do this neither call runs in the database.

I'm not sure if this is related to transactionscope as I haven't tried this without the transaction. This may be occurring normally as well.

A random shot in the dark guess....I read another issue on here stating they wanted temporary tables. What if the temp tables are changing some sort of ID that gets returned from your code that messes with something? I remember reading about issues using something like @@identity in stored procedures with temp tables.

**Comment by tiagoln** [comment]
Hmm, if there is no error and the changes are not persisted it could be something wrong with the transaction. Could you try to use `context.Database.BeginTransaction()` instead of TransactionScope, like in this [example](https://github.com/tiagoln/BulkExtensions#transactions), to see if it works?

**Comment by dberroa** [comment]
Hey, sorry again for jumping the gun. I realized I wasn't using the same database context for the calls so they were probably going in their own transactions or something.

Using the same context made TransactionScope AND context.Database.BeginTransaction() work.

Not sure which is the better to use but either way everything seems to be working now.

Thanks for your help so far.

**Comment by tiagoln** [comment]
No problem, I'm glad it worked out.
