### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by jesp002** [tiagoln/BulkExtensions#46]
Hi, I get following error

Method not found: 'System.Data.Entity.DbContextTransaction System.Data.Entity.Database.get_CurrentTransaction()'.

Any idea ?

Best regards

**Comment by jesp002** [comment]
I get the error when doing a BulkInsert

**Comment by tiagoln** [comment]
Hi there,
Which version of .Net Framework are you using? By the looks of it, it seems you’re missing a reference.

**Comment by jesp002** [comment]
i'm using version 4.6.1

**Comment by tiagoln** [comment]
EF6 or EFCore?

**Comment by jesp002** [comment]
EF6

**Comment by tiagoln** [comment]
Do you have the `System.Data` reference on your project?

**Comment by jesp002** [comment]
yes off course

**Comment by tiagoln** [comment]
Can you post the full stack trace of this exception?

**Comment by jesp002** [comment]
at EntityFramework.BulkExtensions.Extensions.DbContextExtension.GetContextWrapper[TEntity](DbContext context)
   at EntityFramework.BulkExtensions.BulkExtensions.BulkInsert[TEntity](DbContext context, IEnumerable`1 entities, InsertOptions options)
   at ValidateAndSave.Classes.InsertStaging.insertIntoPreStaging_MAIN_ACCOUNTS(Files f, String companycode, DateTime dtImportDatetime, Boolean fullimport) in  E:\BO\StagingDevelopment\ValidateAndSave\InsertStaging.cs:line 184

**Comment by tiagoln** [comment]
Try the following steps to see if it works:

1. Run `Uninstall-Package EntityFramework` in Package Manager Console
2. Delete EntityFramework folder from 'packages' folder
3. Run `Install-Package EntityFramework` in Package Manager Console

**Comment by jesp002** [comment]
There was a package for 6.0.0 and 6.1.3 in the folder.
After reinstalling only the 6.1.3 is in the folder and the BulkInsert is now working.
Thanks a lot!!!

Best regards,
Jeroen

**Comment by tiagoln** [comment]
You're welcome, I'm Glad it worked =D

**Comment by jesp002** [comment]
Me too! Thanks for the very fast help.
