### ISSUE TITLE
SqlBulkTools

### ISSUE THREAD

**Issue by chinarosesz** [tiagoln/BulkExtensions#6]
BulkExtensions library references SqlBulkTools project at the end of this page. Do you know what happened to this project? It seems like the project is no longer active all of the sudden.

**Comment by tiagoln** [comment]
I noticed that, in fact I'm wondering what should I do with the reference. The repository is no longer available and the nuget package is no longer listed, but if you have the page address of the nuget package you can see that the owner is not Greg Taylor any more, instead it says 'zzzprojects'. I suspect they've bought the code from the guy. Check it out: [https://www.nuget.org/packages/SqlBulkTools/](https://www.nuget.org/packages/SqlBulkTools/)
