### ISSUE TITLE
CreateTempTable method doesn't include the schema name

### ISSUE THREAD

**Issue by gustavobmichel** [tiagoln/BulkExtensions#8]
Hi Tiago.

First of all, I think your package works quite well and I have been using it in my project and it works very well.

When upgrading today to the latest version, I have noticed issues when updating records specifically using the method CreateTempTable (SqlHelper.cs line 53) that generated a query like this:
SELECT TOP 0 <Columns> INTO [_Temp_TableName_Generated] FROM [MyTable] AS A LEFT JOIN MyTable AS Source ON 1 = 2 

However, I have set a schema for my table, so once this is executed I receive the following error:
System.Data.SqlClient.SqlException: Invalid object name 'MyTable'.

Hope this helps to reproduce the same issue.

Thanks again,
Gustavo

**Comment by tiagoln** [comment]
Thanks for reporting the bug, I found out the problem, when I changed this command in the recent updates I  forgot to add the schema. I fixed and tested it but I can only upload a new package version tomorrow. I'll leave a message here when I publish the update.

**Comment by Monia1987** [comment]
The same Issue when I trying to use BulkInsertOrUpdate with table which has custom schema (not dbo)

**Comment by tiagoln** [comment]
I've just published a new version(1.3.3) that should fix this issue, please update and check it out :)

**Comment by gustavobmichel** [comment]
Yep, all good. Just tested it and it is working fine. Thanks.

**Comment by tiagoln** [comment]
You're welcome! :)

**Comment by Monia1987** [comment]
Thanks for such a quick update!
All works fine.
