### ISSUE TITLE
CreatedDate and LastModifedDate with BulkInsertUpdate

### ISSUE THREAD

**Issue by chinarosesz** [tiagoln/BulkExtensions#9]
My goal is to have entity framework generate CreatedDate and LastModifedDate when a row is inserted or modified. Currently, I'm keeping track of this manually by setting DateTime.UtcNow whenever a row is updated or inserted (in code). It sucks because sometimes I miss this scenario on some tables. Ideally, I want these two to be populated automatically. I know there is something called a Trigger in SQL, but there's also another way where I can override SaveChanges. However, is it possible if I override BulkInsertUpdate instead of SaveChanges? 

Here's an article that shows how to override SaveChanges to auto populate inserted date and last modified date. http://benjii.me/2014/03/track-created-and-modified-fields-automatically-with-entity-framework-code-first/

**Comment by tiagoln** [comment]
As the BulkExtensions are implemented as extension methods you cannot override the methods, but you can encapsulate the BulkExtensions calls with extension methods of your own, to prepare the entities for your use case. The example below works for this case:
```c#
public static class MyBulkExtension
{
    private const string CreatedDate = "CreatedDate";
    private const string LastModifiedDate = "LastModifiedDate";
    
    public static int MyBulkInsertOrUpdate<TEntity>(this DbContext context, IEnumerable<TEntity> collection, InsertOptions options = InsertOptions.Default) where TEntity : class
    {
        foreach (var entity in collection)
        {
            var props = entity.GetType().GetProperties(BindingFlags.FlattenHierarchy | BindingFlags.Public | BindingFlags.Instance);
                
            var createdDate = props.SingleOrDefault(prop => prop.Name == CreatedDate);
            if (createdDate != null && createdDate.GetValue(entity, null) == null)
            {
                createdDate.SetValue(entity, DateTime.UtcNow, null);
            }
                
            var lastModified = props.SingleOrDefault(prop => prop.Name == LastModifiedDate);
            lastModified?.SetValue(entity, DateTime.UtcNow, null);
        }
        return context.BulkInsertOrUpdate(collection, options);
    }
}
```

And on the places you call `context.BulkInsertOrUpdate(collection)` you'll call `context.MyBulkInsertOrUpdate(collection)`.

**Comment by chinarosesz** [comment]
I think on the second run, created date will reset back to null or whatever the min default date is, and then it will set it to current date time again when calling bulk operation. I have to circle back to the db and get the created date and set it on the entity. Do you know if there is a way to avoid querying for the current created date from DB?

**Comment by tiagoln** [comment]
There is an issue with the 'if' condition of that code exemple I gave you, my bad :P
It was:
`if (createdDate != null && createdDate.GetValue(entity, null) == null)`
Use this if instead: 
`if (createdDate != null && createdDate.GetValue(entity, null).Equals(DateTime.MinValue))`

When a DateTime property is not set it defaults to the min value, I forgot that. This should avoid this issue.

**Comment by chinarosesz** [comment]
Yep that was it!

**Comment by tiagoln** [comment]
Nice, glad I could help :)
